# Nel prototipo didattico si è mantenuto l'accesso anonimo al broker MQTT all'interno della LAN chiusa, 
# delegando l'autenticazione al backend FastAPI

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

listener 1883
allow_anonymous true

listener 9001
protocol websockets
